services:
  postgres:
    image: postgres:15-alpine
    container_name: 3xui_postgres
    environment:
      POSTGRES_USER: 3xui
      POSTGRES_PASSWORD: 3xui_password
      POSTGRES_DB: 3xui_db
    volumes:
      - $PWD/pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped

  3xui:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 3xui_app
    depends_on:
      - postgres
    # hostname: yourhostname <- optional
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
      XUI_DB_TYPE: "postgres"
      XUI_DB_URI: "postgres://3xui:3xui_password@127.0.0.1:5432/3xui_db?sslmode=disable"
    tty: true
    network_mode: host
    restart: unless-stopped
